import './globals.css'
import { Inter } from 'next/font/google'
import Nav from '@/components/Nav'
import { getServerSession } from 'next-auth/next';
import { authOptions } from './api/auth/[...nextauth]/route';

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const session = await getServerSession(authOptions);
console.log({session});
  return (
    <html lang="en">
      <body className={inter.className}>
        <Nav user={session?.user} expires={session?.expires!} />
        <main>
          {children}
        </main>
      </body>
    </html>
  )
}
