import './globals.css'
import { ReactNode } from 'react';
import { Roboto, Lobster_Two } from 'next/font/google'
import Nav from '@/components/Nav'
import { getServerSession } from 'next-auth/next';
import { authOptions } from './api/auth/[...nextauth]/route';
import type { Metadata } from 'next';
import Hydrate from '@/components/Hydrate';

// const inter = Inter({ subsets: ['latin'] })
const roboto = Roboto({weight: ["400", "500", "700"], subsets: ["latin"]})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: {
  children: ReactNode
}) {
  const session = await getServerSession(authOptions);
console.log({session});
  return (
    <html lang="en">
      <body className={roboto.className}>
        <Hydrate>
        <Nav user={session?.user} expires={session?.expires!} />
        <main className='py-12'>
          {children}
        </main>
        </Hydrate>
      </body>
    </html>
  )
}
